dist: xenial
language: python
python:
- 3.7
- 3.8
cache: pip
script:
- python manage.py test
jobs:
  include:
  - install:
    - pip install -r test-requirements.txt
    script: pre-commit run --all-files
